---
- name: Upload custom APT source list (with backports disabled)
  tags: [packages]
  template:
    src: etc/apt/sources.list
    dest: /etc/apt/sources.list
    mode: 0644

- name: Update package cache
  tags: [packages]
  apt:
    update_cache: true

- name: Remove unneeded packages
  tags: [packages]
  apt:
    name: '{{ item }}'
    state: absent
    purge: true
    autoremove: true
  with_items: '{{ ubuntu_base_unneeded_packages + ubuntu_base_additional_unneeded_packages }}'

- name: Upgrade all packages
  tags: [packages]
  apt:
    upgrade: dist

- name: Install needed packages
  tags: [packages]
  apt:
    name: '{{ item }}'
    state: present
  with_items: '{{ ubuntu_base_needed_packages + ubuntu_base_additional_needed_packages }}'
