---
- name: Upload custom APT source list (with backports disabled)
  tags: [packages]
  template:
    src: etc/apt/sources.list
    dest: /etc/apt/sources.list
    mode: 0644

- name: Upgrade all packages
  tags: [packages, slow]
  apt:
    update_cache: true
    upgrade: safe

- name: Install needed packages
  tags: [packages]
  apt:
    name: '{{ item }}'
    state: present
  with_items: '{{ ubuntu_base_needed_packages }}'

- name: Remove unneeded packages
  tags: [packages]
  apt:
    name: '{{ item }}'
    state: absent
    purge: true
    autoremove: true
  with_items: '{{ ubuntu_base_unneeded_packages }}'
