---
- name: Disable APT source packages
  replace:
    path: /etc/apt/sources.list
    regexp: '^deb-src '
    replace: '# deb-src '

- name: Update package cache
  apt:
    update_cache: true

- name: Upgrade all packages
  apt:
    upgrade: true

- name: Install needed packages
  apt:
    name: '{{ item }}'
    state: latest
  with_items: '{{ static.installed_packages + installed_packages }}'
