---
- name: Make sure non-core repositories are enabled
  apt_repository:
    repo: 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release|lower ~ item[1] }} {{ item[0] }}'
    state: present
  with_nested:
    -
      - universe
      - restricted
      - multiverse
    -
      - ''
      - '-security'
      - '-updates'

- name: Update package cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all installed packages
  apt:
    upgrade: true

- name: Install required packages
  apt:
    name:
      - bash
      - sudo
      - locales
      - openssh-server
      - ntp
      - mailutils
      - update-notifier-common
      - unattended-upgrades
      - bash
      - bash-completion
      - vim
      - python-pip
    state: latest

- name: Make sure core Python packages are up to date
  pip:
    name:
      - pip
      - setuptools
    state: latest
