---
- name: Disable `src` repositories
  replace:
    path: /etc/apt/sources.list
    regexp: '^deb-src '
    replace: '# deb-src '

- name: Make sure the `universe` repository is enabled
  apt_repository:
    repo: 'deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release|lower }} universe'
    state: present

- name: Update package cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages
  apt:
    upgrade: true

- name: Install needed packages
  apt:
    name: '{{ static.installed_packages + installed_packages }}'
    state: latest
