---
- name: Restart NTP
  service:
    name: ntp
    state: restarted

- name: Restart Postfix
  service:
    name: postfix
    state: restarted

- name: Register new aliases
  shell: newaliases

- name: Generate locales
  locale_gen:
    name: '{{ item }}'
    state: present
  with_items: '{{ ubuntu_base_needed_locales }}'
